# Generated by Django 4.2.19 on 2025-02-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mealplanoption_customuser_flex_dollars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplanoption',
            options={'ordering': ['meal_swipes']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='meal_plan_balance',
            new_name='meal_swipe_balance',
        ),
    ]
