# Generated by Django 4.2.19 on 2025-04-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mealplanoption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(default='Cafeteria', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('meal', 'Meal Swipe'), ('flex', 'Flex Dollars')], default='Meal Swipe', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='meal_swipe_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
