# Generated by Django 4.2.19 on 2025-04-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_profile_picture_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buddy_swipe_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplanoption',
            name='buddy_swipes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
