# Generated by Django 4.2.19 on 2025-04-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_buddy_swipe_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplanoption',
            old_name='buddy_swipes',
            new_name='buddy_swipe_balance',
        ),
    ]
